### PR TITLE
Fix crash in intrinsicContentSize

### PR DESCRIPTION
**Pull request by jaclync**
Related to https://github.com/quizlet/quizlet-ios/issues/3165

https://fabric.io/quizlet/ios/apps/com.quizlet.quizlet/issues/571f0a10ffcdc042500f0440
- [x] CR @fallenpanda1

### CODE REVIEW

**Comment by fallenpanda1** [comment]
Looks like your fix is slightly different than the one they tried doing upstream: https://github.com/TTTAttributedLabel/TTTAttributedLabel/pull/628/files.

But looking at the Fabric crash, it looks like your fix addresses the immediate crash. :+1:

**Comment by fallenpanda1** [comment]
@jaclync can you give all devs access to this repo? I can't checkmark CR, but it looks good to me! 👍

**Comment by jaclync** [comment]
@fallenpanda1 I just tested that fix upstream, looks like both fix the crash. I slightly prefer not returning `CGSizeZero` as in the upstream PR to just returning super's content size if width < 0

**Comment by jaclync** [comment]
also added iOS team to admin access

**Comment by fallenpanda1** [comment]
:+1:

**Pull request merged**
